server:
  port: 6000
  context-path: /goldfish/data
#  context-path: /

spring:
  redis:
    database: 0
    host: 192.168.1.12
    port: 6379
    password: zjtachao
    pool:
      max-active: 20
      max-idle: 10
      max-wait: 100
      min-idle: 1

  datasource:
    url: jdbc:mysql://192.168.1.11:3306/fish?useUnicode=true&characterEncoding=UTF-8
    username: zjtachao
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-active: 10
      min-idle: 1
      max-wait: 50

mybatis:
  type-aliases-package: com.zjtachao.fish
  config-location: classpath:mybatis/config/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


com:
  zjtachao:
    water:
      goldfish:
        program:
          server:
            path: /attachment/
          http:
            path: https://goldfish.zjtachao.com/attachment/
            prefix: http://
          app:
            id: wxd9e16c68bbfd4b15
            secret: 595d2813985299251741fd46d03fb44c
            url: https://api.weixin.qq.com/sns/jscode2session
          access:
            token:
              url: https://api.weixin.qq.com/cgi-bin/token?
          get:
            wxacode:
              url: https://api.weixin.qq.com/wxa/getwxacodeunlimit?access_token=


goldfish:
  websocket:
    address: ${GOLD_SOCKET_ADDRESS}
    message:
      rest: /goldfish/data/webSocket/message/send

logging:
  level:
    com:
      zjtachao:
        fish:
          goldfish:
            data:
              mapper: debug